# Generated by Django 4.1.5 on 2023-01-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_labels_product_label_remove_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
