# Generated by Django 4.1.5 on 2023-01-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='slug',
            field=models.TextField(default='Product'),
        ),
    ]
