# Generated by Django 4.1.5 on 2023-01-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_inforamtion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inforamtion',
        ),
    ]
