# Generated by Django 4.1.5 on 2023-01-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_inforamtion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
