# Generated by Django 4.1.5 on 2023-01-20 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_check_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='items',
        ),
    ]
