# Generated by Django 4.1.5 on 2023-01-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_check_items_remove_check_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
