# Generated by Django 4.1.5 on 2023-01-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='name',
        ),
    ]
