# Generated by Django 4.1.5 on 2023-01-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_check_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
