# Generated by Django 4.1.5 on 2023-01-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='check',
            name='total',
        ),
    ]
