# Generated by Django 4.1.5 on 2023-01-26 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_check_quantity_remove_check_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
